## Homework 1

- Write on a piece of paper an algorithm that multiplies two matrices.

- Implement your code using Python.

In [1]:
import numpy as np
# We use numpy for generating random matrices, but it is not necessary
# Lists can be used instead.

# This script multiplies two matrices using loops.

# Generate random Matrices. The dimensions can be changed or
# you can enter the matrices manually
A = np.random.rand(5,7)
B = np.random.rand(7,3)

# Define the matrix for the results
C = np.zeros((len(A),len(B[0])))

# Iterate over rows
for i in range(len(A)):
    # Iterate over columns
    for j in range(len(B[0])):
        val = 0
        # Iterate on chosen row and column
        for k in range(len(A[i])):
            val += A[i,k]*B[k,j]
        C[i,j] = val

print(C)
print(A@B)

[[1.43872973 2.40885669 1.25236109]
 [1.13953359 1.47445019 1.12836444]
 [0.91732539 1.41636587 1.06020018]
 [1.95388201 2.72197717 1.67680468]
 [0.77539634 1.23473318 0.56441482]]
[[1.43872973 2.40885669 1.25236109]
 [1.13953359 1.47445019 1.12836444]
 [0.91732539 1.41636587 1.06020018]
 [1.95388201 2.72197717 1.67680468]
 [0.77539634 1.23473318 0.56441482]]
