In [4]:
# import library
import numpy as np

# Example 1

In [93]:
A = np.array([[1,2,3]])
print("Matrix A:")
print(A,"\n")

B = np.array([[1],[1],[0]])
print("Matrix B:")
print(B)

Matrix A:
[[1 2 3]] 

Matrix B:
[[1]
 [1]
 [0]]


# Example 2

In [94]:
A = np.array([[1,2,3],[4,5,6],[1,2,3]])
print("Matrix A:")
print(A,"\n")

B = np.array([[1,1,0],[1,0,1],[1,1,1]])
print("Matrix B:")
print(B)

Matrix A:
[[1 2 3]
 [4 5 6]
 [1 2 3]] 

Matrix B:
[[1 1 0]
 [1 0 1]
 [1 1 1]]


# Example 3

In [95]:
A = np.array([[1,1,2,2],[2,2,1,1],[1,1,1,2]])
print("Matrix A:")
print(A,"\n")

B = np.array([[2,3],[4,5],[6,7],[8,9]])
print("Matrix B:")
print(B)

Matrix A:
[[1 1 2 2]
 [2 2 1 1]
 [1 1 1 2]] 

Matrix B:
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


# Matrix Multiplication code

In [77]:
def MatrixMultiplication(a,b):
    '''
    given any matrix A and B, this function perform
    a matrix multiplication between them if it can be done.
    '''
    C = np.zeros([A.shape[0],B.shape[1]]) # Result matrix shape.
    if (A.shape[1] != B.shape[0]): return print("ERROR") # if A dim is (n1xm1) and B dim is (n2xm2), multiplication can be done if m1=n2.
    else:
        r = A.shape[1]
        for i in range(A.shape[0]):
            for j in range(B.shape[1]):
                for k in range(r):
                    C[i,j] += A[i,k]*B[k,j] 
    
    return C

# Result 1

In [87]:
d = MatrixMultiplication(A,B)
print(d)

[[3.]]


# Result 2

In [89]:
d = MatrixMultiplication(A,B)
print(d)

[[ 6.  4.  5.]
 [15. 10. 11.]
 [ 6.  4.  5.]]


# Result 3

In [91]:
d = MatrixMultiplication(A,B)
print(d)

[[34. 40.]
 [26. 32.]
 [28. 33.]]
