## Modelado de datos con Redes Neuronales: Class 2

## Vocabulary
* stuff - cosas
* staff - personel
* remarks - comentarios
* at least - por lo menos
* skills - habilidades
* give someone a credit for something - apreciar alguien por algo
* take it easy
* guys - chicos
* obviously - obvio
* hints - pistas
* feature - caracteristica
* creepy - miedoso
* mentioned - mensionado

## Order of the class:
* organization stuff 
    * remarks on language (if you are already great in NN at least you can improve you English skills)
    * lets make it interactive
    * github and homeworks submissions
    * lets take it easy we have time (no strike planned)
* from general to details
* hints on programming and doing homeworks
* machine learning basics
* types of algorithms


* visualization using Matplotlib
* crash course on image processing 

## How to learn things
- avoid copy and paste
- memorize most common commands (same as English language) - make your own "dictionary"
- plan before you code (write on a piece of paper then copy) - it will give you a satisfaction if your code works
- close your computer and reflect!
- do your homework!!! Ask questions

## The challenge of machine learning 
(human's world complexity)
* example: image
* how would you recognized a cat on an image?
* checking if pixels form a shape of a cat * using "if" "else if" syntax???


* example: voz
* how would you convert human speach to text - speach recognition
* can this be simply done using programming syntax: "if" "else if"?

  <img src="imgs/speach_recognition.png" width="500" />
  
  * take into account different accents
  * vocabulary
  * what if there is new vocabulary?
  * how would you define a set of complex rules if, else...
  * to decide which word correspond to which object?
  * ordering pizza by voice command that would result computer to take an action and call a pizzeria.... 
  * even if you could do it, it would still not be flexible enough to recognize new words!
* machine learning allows us to automatically learn these complex rules efficiently from labeled examples - called training data
* statistical learning (humans also make errors)

## Machine Learning definition

* The term Machine Learning was coined by Arthur Samuel in 1959, an American pioneer in the field of computer gaming and artificial intelligence, and stated that “it gives computers the ability to learn without being explicitly programmed”.


* And in 1997, Tom Mitchell gave a “well-posed” mathematical and relational definition that “A computer program is said to learn from experience E with respect to some task T and some performance measure P, if its performance on T, as measured by P, improves with experience E.
(Se dice que un programa de computadora aprende de la experiencia E con respecto a alguna tarea T y alguna medida de desempeño P, si su desempeño en T, medido por P, mejora con la experiencia E )


* Wikipedia: Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence....

## How the machines can learn by themselves - example
* example: apple
* if there was a person that has never seen an apple and you showed him an image of an apple 

<img src="imgs/apple_1.png" width="300" />

* and then show him different image of an apple 
* he could most probably make a mistake because: he could even confuse it with apricot... because he $\textbf{learned}$ that apple is red, round, has the stem 

<img src="imgs/apple_2.png" width="300" />

* but if we showed that person 100 different apples and $\textbf{label}$ them as "apple" he starts thinking ok, (so apple un grupo de frutas... un especie), so there is a pattern 

<img src="imgs/apples.png" width="1000" />

* why? Because all apples they have something in common!!!

  * skin (texture)
  * size (smaller than watermelon)
  * stem 
  * dimple
  * color (red, yellow, green with shades...)
  * feature correlation (ajuste)
  
<img src="imgs/apple_diagram.png" width="400" />

* recognizing an apple can even simple animal so its not about true thinkig or inteligence (chicken)
* so computer can find those "correlations"
* computer can learn like a baby from the "experience"
* sample + label is all what it needs to generalize the problem (for this particular problem)
* how? we need to understand how fitting works
* there is a lot of math behind all of this (convolution, correlation, regression...)
* so the idea behind machine learning is to make computers learn by themselves


* Apart from some creepy news on Machine Learning there are also a great things:

https://news.stanford.edu/news/2008/september10/helicopter-091008.html

https://www.youtube.com/watch?v=M-QUkgk3HyE

https://newatlas.com/robotic-helicopter-teaches-itself-how-to-fly-aerobatics/11621/

https://www.youtube.com/watch?v=W_gxLKSsSIE (... reinforced learning)

https://tectales.com/bionics-robotics/self-learning-robots-go-full-steam-ahead.html


## Different algorithm for different problem

* recognizing an apple is just one type of a problem
* not all methods are good in recognizing an apple, in this particular task CNN are the best
* so there are different methods for different tasks
* if something is apple or not an apple is called a clasification problem
* the problems that the "machines" will encounter in human world are of different types (not only categorization, also optimization, prediction, regression, clustering): 

### Machine Learning by problem (or algorithm):

<img src="imgs/machine_learning_types.png" width="500" />

###  Difference between supervised and unsupervised learning (focus on level 1):

<img src="imgs/machine_learning_types2.png" width="500" />

###  Different types of supervised/unsupervised learning (focus on level 2):
<img src="imgs/machine_learning_types4.png" width="800" />

###  Examples of types of supervised/unsupervised learning (level 2):
* Supervised learning
  * regression (continues values: house prices predicition based on house size)
  <img src="imgs/regression_problem.png" width="500" />
  * classification (discrete values: based on many images and labels predict or classify fruits, people, but also binary: yes/no, cancer benigno/maligno? but all with labels)
 <img src="imgs/classification_problem.png" width="700" />
* Unsupervised learning
  * clustering (organizing articles based on topic, context, NO labels)
  <img src="imgs/clustering_problem.png" width="500" />
  https://news.google.com
  https://www.niemanlab.org/2020/04/france-is-the-latest-european-country-to-demand-that-google-pay-news-orgs-for-including-their-stories-in-search/
  * association (what people buy together: clothes and watches)
  <img src="imgs/association_problem.png" width="500" />
  * dimensionality reduction
  autoencoders...PCA
  <img src="imgs/dimensionality_reduction.png" width="500" />

##  How to choose the algorithm or assign the algorithm to a problem:

    * are the labels necessary?
        * yes - supervised learning
            * are the variables continuous or discrete
                * discrete: classification problem
                * continuous: regression problem 
        * no  - unsupervised learning
            * clustering
            * dimensionality reduction
            * association

## Quiz
Q1.
https://poll-maker.com/poll3974657x5cAb877E-126

Q2.
https://poll-maker.com/poll3974653x0CA2456f-126 

Q3.
https://poll-maker.com/poll3974415x376049EF-126 

Q4.
https://poll-maker.com/poll3974356x370173b8-126 

Q.5.
https://poll-maker.com/poll3988357xC0804A00-126

## What to use and when
This is not obvious, but just for orientation... lets look at the cheat sheet:
<img src="imgs/CheatSheet2.png" width="1200" />
  https://blogs.sas.com/content/subconsciousmusings/files/2017/04/machine-learning-cheet-sheet.png

## Machine learning is lot of data
What data will we work with?

* images - Matplotlib
    * visualizing them
    * checking dimensions
    * RGB to gray scale conversion
    * reshaping with numpy
* tables with columns and rows of data - Pandas
    * dictionaries
    * creating and saving panda dataframes
    * loading dataframes from files
    * data manipulation
* spectroscopy signals...
    * Python and OS
    * loading data from nested directories

## Homework 1 (can you do this?:)
* write on a piece of paper an algorithm that multiplies two matrices A, B (using loops only)

<img src="imgs/matrix_multiplication.png" width="500" />

* implement your code using python and check if your result is correct using A@B.

In [18]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=A.T
A@B

array([[14, 32],
       [32, 77]])

In [17]:
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
