## Homework 1

- Write on a piece of paper an algorithm that multiplies two matrices.

- Implement your code using Python.

In [23]:
import numpy as np
# We use numpy for generating random matrices, but it is not necessary
# Lists can be used instead.

# This script multiplies two matrices using loops.

# Generate random Matrices. The dimensions can be changed or
# you can enter the matrices manually
A = np.random.rand(5,7)
B = np.random.rand(7,3)

# Define the matrix for the results
C = np.zeros((len(A),len(B[0])))

# Iterate over rows
for i in range(len(A)):
    # Iterate over columns
    for j in range(len(B[0])):
        val = 0
        # Iterate on chosen row and column
        for k in range(len(A[i])):
            val += A[i,k]*B[k,j]
        C[i,j] = val

print(C)
print(A@B)

This script multiplies two matrices using loops.
[[1.90338911 1.76784091 1.76609576]
 [2.35782192 2.72173262 1.86105162]
 [2.97168019 3.39295398 2.54883051]
 [2.54673393 2.96388873 2.1809978 ]
 [2.58953443 2.62190967 2.07872195]]
[[1.90338911 1.76784091 1.76609576]
 [2.35782192 2.72173262 1.86105162]
 [2.97168019 3.39295398 2.54883051]
 [2.54673393 2.96388873 2.1809978 ]
 [2.58953443 2.62190967 2.07872195]]
