### Homework 1

**Santiago Tabares Garcés**

**1036666894**

* write on a piece of paper an algorithm that multiplies two matrices A, B (using loops only)

* implement your code using python and check if your result is correct using A@B.

In [5]:
import numpy as np

In [6]:
def mult(A,B):
    result = np.zeros((np.shape(A)[0],np.shape(B)[1]))
    if np.shape(A)[1] != np.shape(B)[0]:
        print("Can't multiply, check dimensions..")
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j] 
    return result


In [7]:
A=np.array([[1,2,3],[4,5,6]])
B=A.T

C = mult(A,B)

print("Matrix A:\n",A)
print("")
print("Matrix B:\n",B)
print("")

print("The result A*B using the function is: \n", C)
print("")
print("The result A*B using A@B is:\n", A@B)


Matrix A:
 [[1 2 3]
 [4 5 6]]

Matrix B:
 [[1 4]
 [2 5]
 [3 6]]

The result A*B using the function is: 
 [[14. 32.]
 [32. 77.]]

The result A*B using A@B is:
 [[14 32]
 [32 77]]


-----------------


In [8]:
# Using other values of A and B
A = np.array([[1,3,5,6],[8,92,19,1],[8,90,10,2],[1,3,5,9]])
B = np.array([[10,4,1,6],[8,1,15,1],[3,4,8,2],[9,3,5,9]])

C = mult(A,B)

print("The result A*B using the function is: \n", C)
print("")
print("The result A*B using A@B is: \n", A@B)




The result A*B using the function is: 
 [[ 103.   45.  116.   73.]
 [ 882.  203. 1545.  187.]
 [ 848.  168. 1448.  176.]
 [ 130.   54.  131.  100.]]

The result A*B using A@B is: 
 [[ 103   45  116   73]
 [ 882  203 1545  187]
 [ 848  168 1448  176]
 [ 130   54  131  100]]
