# TensorFlow - semiformal introduction

* developed by Google Brain team
* backend in C/C++ so its faster than pure Python
* main task: Machine learning and Deep Neural Networks (created for that)
* lot of build-in mathematical functions for NN
* well optimized
* can perform parallel computing
* supports CPU, GPU 

## TF structure is based on dataflow graph
* this part is just to make you aware of the depth of TensorFlow as framework

<table><tr>
<td> <img src="imgs/tf_graph.png" width="800" /> </td>
</tr></table>

    * nodes: mathematical operations
    * edges: multidimensional arrays (tensors TensorFlow)   
    * standard usage is build >> execute
    * tensors: examples
    * example of 3D tensor color image (RGB)
    * in data flow graph the NODES are called operations - units of computation
    * the edges are tensors (data produces by mathematical operation)
    * tf.placeholder() - hole through the graph can be feeded with data (feature matrix)
    * we initialize the placeholders before using them
    * tf.Variable() is a matrix of variables (coefficients: $\theta$s)
    * weight matrix and feature matrix is matrix multiplication:

$$ \theta =
\begin{bmatrix}
\theta_{0} \\
\theta_{1} \\
\theta_{2} \\
\vdots\\
\theta_{n}
\end{bmatrix}
$$

$$ X=
\begin{bmatrix}
1 \\
x_{1} \\
x_{2} \\
\vdots\\
x_{n}
\end{bmatrix}
$$
      $$\theta^TX = \theta_0 + \theta_1 x_1 + \theta_2 x_2$$
* the output of each operation is a tensor      

### Tensorflow architecture

<table><tr>
<td> <img src="imgs/tf_architecture.png" width="700" /> </td>
</tr></table>

* front end - the interaction part - building the code in Python is simple and quick
* the powerr of Tf is that you can build it once and run on anything even mobile phone

### TensorFlow 2.x and "Eager Execution" 
* TF 2.0 big improvement:
   * Keras is a part of TF - high-level API
   * Keras is for NN - very user friendly
   * Keras does not have his own execution engine! so it depened on other framework like     Theano or Pytorch, or TensorFlow
   * performance optimization and support for CPU and GPU acceleration
   * new feature: eager execution

In [23]:
# this was old tensorflow v1

# You will not really need this - its just to explain some elements
# we initialize two tensors a,b  
import tensorflow as tf
import tensorflow.compat.v1 as tf
import numpy as np
a=tf.constant(np.array([1.0,2.0,3.0]))
b=tf.constant(np.array([4.0,5.0,6.0]))
c=tf.tensordot(a,b,1)
print(type(c))
print(c)
# until here nothing happens

# when one creates "session" then the value is assigned to 'c'
session = tf.Session()
output = session.run(c)
session.close()

# that made TF code hard to debug

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(32.0, shape=(), dtype=float64)


RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

* until here TF was not so popular
* eager execution mean the code is executed "line-by-line" and intermediate results are accesible

In [39]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
import numpy as np
a=tf.constant(np.array([1.0,2.0,3.0]))
b=tf.constant(np.array([4.0,5.0,6.0]))
c=tf.tensordot(a,b,1)
c.numpy()

32.0

# Basically tensorflow has his own datatype

In [41]:
import tensorflow as tf

var1=tf.ones([1,2,3])
var2=tf.zeros([2,3,2])
print(type(var1))
print(var2)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(2, 3, 2), dtype=float32)


In [29]:
# But we can still use Numpy (and we will)

In [42]:
import numpy as np

var3=np.zeros([2,3,2])
var4=np.ones([1,2,3])
print(type(var3))
print(var3)

<class 'numpy.ndarray'>
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


# First example with TensorFlow

#### mnist digits classification using TensorFlow Neural Network - very quick guide - all will be explained better later

# Principle elements of building Neural Network using TensorFlow:

* prepare the data
  * data X_train,y_train X_test,y_test (using scikit-learn )
* create a sequential model
  * model.compile
  * model.fit
  * model.evaluate
  * model.predict

### Sequential model accepts different layers
InputLayer, Dense, Flatten, Conv2D, MaxPool2D, Dropout)

* InputLayer specifies the input shape of the data (mnist)
   * how to get the proper dimensions: X_train[0].shape
* Dense is a standard neural network layer
   * dense accepts number of neurons and the activation function and label 

In [43]:
import tensorflow as tf

In [44]:
from tensorflow.keras.models import Sequential

In [47]:
from tensorflow.keras.layers import Dense, Softmax, InputLayer

Must read the documentation!
type: tensorflow InputLayer

In [ ]:
model=Sequential([InputLayer(input_shape=(784,)),
                  Dense(units=16,activation='relu',name='hidden_relu'),
                  Dense(units=10,activation='softmax',name='output_softmax')
                 ])

In [ ]:
model.summary()

### Compile the model with given parameters
* optimizer (adam,sgd)
* loss function, for mnist try: 'sparse_categorical_crossentropy'
* metrics (most common is accuracy) (how to measure the performance of the NN)

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

### Fitting (training) the model with given parameters
* accepts X_train,y_train (and evaluation data ... later)
* epochs - number of passes (remember gradient descent)
* batch_size like a size of a package (default is 32)

In [ ]:
mhistory=model.fit(X_train, y_train, epochs=10, batch_size=32)

myhistory is to visualize the progres (is a dictionary )

In [ ]:
print(myhistory.history.keys())

### Predict (check the model state of training)

In [38]:
# accepts slices of data. Use X_test for prediction
pred = model.predict(X_test[0:1,:])

NameError: name 'model' is not defined