In [1]:
import numpy as np
#import matplotlib.pyplot as plt
#%matplotlib inline

In [2]:

def matriz_mult(A,B):# multiplicación de matrices AB = C
    C = [] 

    for i in range(len(A)):

        fila = [] # fila de la nueva matriz
        for j in range(len(B[0])):

            producto = 0 # Se inicia para almacenar los elementos de la nueva matriz  

            for k in range(len(A[i])):
                 producto += A[i][k] * B[k][j]#se fija un i y un j, se itera sobre k para cada elemento  
            fila.append(producto) # se llena la lista fila de cada una de los elementos  

        C.append(fila) # se llena la nueva matriz con las filas en el loop anterior  
    return C 

In [3]:
A=np.array([[1,2],[2,3]])
B=np.array([[1,2],[2,3]])

range(len(A))
C_= A@B
C_

array([[ 5,  8],
       [ 8, 13]])

In [4]:
C= np.array(matriz_mult(A,B))
C

array([[ 5,  8],
       [ 8, 13]])

In [5]:
C==C_

array([[ True,  True],
       [ True,  True]])