# Homework 1 Matrix multiplication

## Daniel Sierra Botero C.C. 1152216176

Write an algorithm that multiplies two matrices A, B (using loops only) check if your result is correct using A@B.

In [20]:
import numpy as np

In [21]:
#problem matrix
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[0,7]])

In [22]:
def MatrixMultiplications(matrix_a,matrix_b):
    #check if multiplication is possible
    if (np.shape(matrix_a)[1] != np.shape(matrix_b)[0]):
        print('Error: check dimensions of arrays')
        exit()
    #multiplication using for loops
    else:
        C = np.zeros((np.shape(matrix_a)[0],np.shape(matrix_b)[1]))
        for i in range(np.shape(matrix_a)[0]):
            for j in range(np.shape(matrix_b)[1]):
                for k in range(np.shape(matrix_a)[1]):
                    C[i,j] = C[i,j] + matrix_a[i,k]*matrix_b[k,j]
                    
    return(C)

In [23]:
MatrixMultiplications(A,B)

array([[ 5., 20.],
       [15., 46.]])

In [24]:
A@B

array([[ 5, 20],
       [15, 46]])

Other examples

In [25]:
C = np.array([[1,5,2],[3,2,4]])
D = np.array([[5,6],[0,7],[3,7]])

In [26]:
MatrixMultiplications(C,D)

array([[11., 55.],
       [27., 60.]])

In [27]:
C@D

array([[11, 55],
       [27, 60]])

In [28]:
E = np.array([[8,5,0],[3,3,4],[1,0,7]])
F = np.array([[2,3],[0,7],[3,7],[0,4]])

In [29]:
MatrixMultiplications(E,F)

Error: check dimensions of arrays


SystemExit: 

In [30]:
E@F

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)