#Homework 1
##Rafael Barrera Quiroz C.C. 1035433047

### Escriba un algoritmo que multiplique dos matrices, utilizando solo cliclos _for_

In [1]:
import numpy as np

def Multiplicacion(A,B):  #Calcula el producto A*B
  if np.shape(A)[1]==np.shape(B)[0]:  #Debe satisfacerse que el numero de columnas de A sea igual al numero de filas de B
    lista=[]
    lista1=[]
    for i in range(np.shape(A)[0]):
      for j in range(np.shape(B)[1]):
        for k in range(np.shape(A)[1]):
          lista.append(A[i,k]*B[k,j]) #Definicion de producto matricial desde el algebra lineal
    lista=np.array(lista)
    lista2=np.split(lista,np.shape(A)[0]*np.shape(B)[1])
    for i in range(len(lista2)):
      lista1.append(np.sum(lista2[i]))
    resultado=np.reshape(lista1,(np.shape(A)[0],np.shape(B)[1]))
    return resultado
  else:
    return 'producto matricial no definido'

In [3]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[0,7]])

print(A@B)
print('\n',Multiplicacion(A,B))

[[ 5 20]
 [15 46]]

 [[ 5 20]
 [15 46]]


In [5]:
R=np.array([[2,1,-1,0],[3,-2,0,5],[-2,1,4,2]])
Q=np.array([[5,-3,1],[1,2,0],[-1,0,4],[0,-2,3]])

print(R@Q)
print('\n')
print(Multiplicacion(R,Q))

[[ 12  -4  -2]
 [ 13 -23  18]
 [-13   4  20]]


[[ 12  -4  -2]
 [ 13 -23  18]
 [-13   4  20]]


In [6]:
R=np.array([[-3,7,2]])
Q=np.array([[1,4,-5]]).T

print(R@Q)
print('\n')
print(Multiplicacion(R,Q))

[[15]]


[[15]]
