In [1]:
!ls

class_4.ipynb  fruit_data_with_colors.txt


# Modelado de datos class: 5

## Vocabulary:
* common - comun
* features - caracteristicas
* labels - etiquetas
* targets - meta o valor previsto
* just - solamente
* using - usando
* unique - unicos
* one can get - uno puede consequir
* lookup_table - tabla_de_conversion
* tips - pistas
* usually - usualmente



* through - a taves
* keys - llaves
* values - valores
* dictionary - dictionario

# Converting input data (pandas / dictionaries) into a training data

usually in ML algorithms the input and output have common name:
**X_data** - input data or features
**y_data** - labels / targets
data enters in three forms
* images
* dictionary (sklearn)
* csv files / txt fiels - PANDAS
* MAT (Matlab)
  * import scipy.io
  * dictionary = scipy.io.loadmat('data.mat')

The simples way to load data into a Neural Network is to convert the data into a numpy array

## Pandas

1)
* you can convert entire panda dataframe into a numpy arra:
  df_np = df.to_numpy()
* you can also convert some columns to to nupy
  xvalues = df['xvalues'].to_numpy()
  
2) make a look up table:
*  dict(zip(df['xvalues'].unique(),df['yvalues'].unique()))  

In [2]:
import numpy as np
import pandas as pd
df_fruits = pd.read_csv('fruit_data_with_colors.txt',sep='\t')

In [3]:
df_fruits.head()

fruit_label fruit_name  fruit_subtype  mass  width  height  color_score
0            1     apple   granny_smith    192    8.4     7.3         0.55
1            1     apple   granny_smith    180    8.0     6.8         0.59
2            1     apple   granny_smith    176    7.4     7.2         0.60
3            2  mandarin       mandarin     86    6.2     4.7         0.80
4            2  mandarin       mandarin     84    6.0     4.6         0.79

In [4]:
lookup_table=dict(zip(df_fruits['fruit_label'].unique(),df_fruits['fruit_name'].unique()))

In [5]:
lookup_table[2]

'mandarin '

In [6]:
df_fruits_np = df_fruits.to_numpy()
df_fruits_np.shape

(59, 7)

In [7]:
X_data = df_fruits[['mass','width','height','color_score']].to_numpy()

In [8]:
X_data[0:4]

array([[192.  ,   8.4 ,   7.3 ,   0.55],
       [180.  ,   8.  ,   6.8 ,   0.59],
       [176.  ,   7.4 ,   7.2 ,   0.6 ],
       [ 86.  ,   6.2 ,   4.7 ,   0.8 ]])

In [9]:
y_data = df_fruits[['fruit_label']].to_numpy()

In [10]:
y_data[0:4]

array([[1],
       [1],
       [1],
       [2]])

In [11]:
X_data.shape

(59, 4)

In [12]:
num_samples = X_data.shape[0]
print(num_samples)

59


In [13]:
rand_idx = np.random.randint(0,num_samples,10)

In [14]:
rand_idx


array([45, 32, 22,  6, 54, 48, 14, 55, 52, 32])

In [15]:
X_data[rand_idx]

array([[186.  ,   7.2 ,   9.2 ,   0.72],
       [164.  ,   7.2 ,   7.  ,   0.8 ],
       [140.  ,   7.3 ,   7.1 ,   0.87],
       [ 80.  ,   5.9 ,   4.3 ,   0.81],
       [116.  ,   6.1 ,   8.5 ,   0.71],
       [174.  ,   7.3 ,  10.1 ,   0.72],
       [152.  ,   7.6 ,   7.3 ,   0.69],
       [116.  ,   6.3 ,   7.7 ,   0.72],
       [118.  ,   5.9 ,   8.  ,   0.72],
       [164.  ,   7.2 ,   7.  ,   0.8 ]])

In [16]:
y_data[rand_idx]

array([[4],
       [3],
       [1],
       [2],
       [4],
       [4],
       [1],
       [4],
       [4],
       [3]])

In [17]:
lookup_table[4]

'lemon '

# Extract data from dictionary (values are usually a numpy array)

* to inspect dictionary use:
    dictionary.keys()
* if there is ['DESCR']
* print(dictionary['DESCR']) (scikit - always has it)
* key: ['data'] - X_data
* key: ['target'] - labels or **y_data**
* key: ['target_name']
* lookup_table will be made a different way than in Panda
* dict(zip(np.unique(iris['target']),np.unique(iris['target_name']))
* sklearn.utils.Bunch is extended dictionary

In [18]:
# Example:
from sklearn import datasets
iris = datasets.load_iris()

In [19]:
type(iris)

sklearn.utils.Bunch

In [20]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [21]:
print(iris['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [22]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [23]:
lookup_table = dict(zip(np.unique(iris['target']),np.unique(iris['target_names'])))

In [24]:
lookup_table[0]

'setosa'

In [25]:
X_data=iris['data']

In [26]:
y_data = iris['target']

In [27]:
X_data[0]

array([5.1, 3.5, 1.4, 0.2])

In [28]:
y_data[0]

0

In [29]:
idx=np.random.randint(0,X_data.shape[0],10)

In [30]:
idx

array([62, 26, 38, 25, 84, 45, 16, 18, 84, 79])

In [31]:
X_data[idx]

array([[6. , 2.2, 4. , 1. ],
       [5. , 3.4, 1.6, 0.4],
       [4.4, 3. , 1.3, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.4, 3. , 4.5, 1.5],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5.4, 3. , 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ]])

In [32]:
y_data[idx]

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 1])

# Once you have X_data and y_data you can separate them by different sets:
* training set
* test set

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test, y_train,y_test= train_test_split(X_data,y_data,random_state=11,test_size=0.2)

In [35]:
X_train.shape

(120, 4)

In [36]:
y_train.shape

(120,)

In [37]:
X_test.shape

(30, 4)

In [38]:
X_train[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [5. , 3.3, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [6.7, 3. , 5. , 1.7],
       [5.5, 3.5, 1.3, 0.2],
       [6. , 2.7, 5.1, 1.6]])

In [39]:
import tensorflow as tf

In [40]:
#tf.random.set_seed(10)

In [50]:
np.random.seed(10)

In [72]:
#np.random.seed(10)
np.random.randint(0,100,3)

array([ 0, 40, 36])