# Home work 1

### Student name:
    Joseph Nicolay Ruiz Alvarez
    
#### Description
    Construct an algorithm to compute the matrix multiplication using loops.

In [4]:
#Chargin uselful libraries
import numpy as np

In [65]:
class Matrix:
    
    "It is a class of matrix of orden nxm. Input a list with dimensio (n,m)"
    
    def __init__(self, data):
        self.data = np.array(data)
        self.size = np.array(data).shape
        
        
    def __mul__(self, other):
        """ Return the matrix product. If 'other' is scalar, it multiplies each component by the input"""
        
        if type(other) == type(self):        
                   
            if self.size[1]==other.size[0]:
                M = np.zeros((self.size[0],other.size[1]))

                for i in range(self.size[0]):
                    for j in range(other.size[1]):
                        sum=0
                        for k in range(self.size[1]):
                            sum+=self.data[i][k]*other.data[k][j]
                        M[i][j]=sum
                return Matrix(M)
            else:
                return print("Error, invalid multiplication. The matrices dimensions are incompatible")
            
        
        elif type(other) == type(1) or type(other) == type(1.0) or type(other)==type(1.0j):
            M = other*self.data
            return Matrix(M)
        
        else:
            return print('Invalid input. Check, and try again')

    def print(self):
        '''Print the matrix'''
        return print('Matrix \n {}'.format(self.data))

    



In [67]:
#instance a object A and B
A = Matrix([[1,2,3],[1,0,0],[1,1,1]])
A.print()
B = Matrix([[1,2],[2,3],[5,6]])
B.print()
#Multiply them
C = A.__mul__(B)
C.print()
print('Dimension of matrix is: {}'.format(C.size))

#Scalar multiplication 
D = C.__mul__(2.0+1j)
D.print()


Matrix 
 [[1 2 3]
 [1 0 0]
 [1 1 1]]
Matrix 
 [[1 2]
 [2 3]
 [5 6]]
Matrix 
 [[20. 26.]
 [ 1.  2.]
 [ 8. 11.]]
Dimension of matrix is: (3, 2)
Matrix 
 [[40.+20.j 52.+26.j]
 [ 2. +1.j  4. +2.j]
 [16. +8.j 22.+11.j]]
