# Homework 1

Andrés Muñoz Acevedo

cc :1037663477

* Write on a piece of paper an algorithm that multiplies two matrices A, B (using loops only)
* implement your code using python and check if your result is correct using A@B.


In [39]:
def matrix_multiplie(A,B):
    
    
    C = np.zeros((len(A),len(B[0])))
    for i in range(len(A)):
        
        if len(A[i]) != len(B): 
            print('The operation fails. Check the dimensions!')
            return 
        
        for h in range(len(B[i])):
            c = 0
            for j in range(len(A[i])): 
            
                c += A[i,j]*B[j,h]
            C[i,h] = c
        
    return C

In [40]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=A.T # ([1,4],[2,5],[3,6])
print(matrix_multiplie(A,B))
print(A@B)

print(matrix_multiplie(A,B) == A@B)

[[14. 32.]
 [32. 77.]]
[[14 32]
 [32 77]]
[[ True  True]
 [ True  True]]


In [43]:
A=np.array([[1,2,3,54],[4,5,6,65],[90,512,34,78]])
B=np.array([[1,3,54],[4,5,65],[512,34,78],[512,34,78]]) # ([1,4],[2,5],[3,6])

print(matrix_multiplie(A,B))
print(A@B)

print(matrix_multiplie(A,B) == A@B)

[[29193.  1951.  4630.]
 [36376.  2451.  6079.]
 [59482.  6638. 46876.]]
[[29193  1951  4630]
 [36376  2451  6079]
 [59482  6638 46876]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
